// ================================================================
//  POPPY WORDY – Centralised Game Configuration
//  ──────────────────────────────────────────────────────────────
//  This is the ONLY file you need to edit for tuning the game.
//  All physics, grid, language and visual constants live here.
// ================================================================

// ── Canvas ─────────────────────────────────────────────────────
export const CANVAS_WIDTH = 480;
export const CANVAS_HEIGHT = 760;

// ── Hex Grid ────────────────────────────────────────────────────
export const GRID = {
  /** Pixel radius of each bubble (also controls overall scale).  */
  bubbleRadius: 28,

  /** Number of hex columns across the screen. */
  cols: 8,

  /** Maximum number of rows before game-over is triggered. */
  maxRows: 22,

  /** Number of pre-filled rows at game start. */
  startRows: 0,

  /** Y-pixel offset for the first row from the canvas top. */
  topPadding: 100,

  /** Left margin: distance from canvas edge to first column centre. */
  leftMargin: 28,
};

/**
 * Vertical distance between hex row centres.
 * For a honeycomb grid: rowHeight = radius * sqrt(3) ≈ radius * 1.732
 */
export const HEX_ROW_HEIGHT: number = GRID.bubbleRadius * Math.sqrt(3);

// ── Y limit for game-over ────────────────────────────────────────
/** If any bubble row centre goes below this Y, game is over. */
// This should be used as: this.scale.height - 130 in scenes.
export const GAME_OVER_OFFSET = 130;

// ── Physics ─────────────────────────────────────────────────────
/**
 * All physics constants are grouped here for easy fine-tuning.
 *
 * ── TUNING GUIDE ────────────────────────────────────────────────
 *  launchSpeed      → controls how fast the bubble travels
 *  wallBounceFactor → 1.0 = perfectly elastic; <1 = damped
 *  minFlickDistance → prevents accidental micro-taps
 * ────────────────────────────────────────────────────────────────
 */
export const PHYSICS = {
  /** Maximum possible launch speed (px/s). */
  maxLaunchSpeed: 2400,

  /** Minimum launch speed to ensure it doesn't just fall (px/s). */
  minLaunchSpeed: 400,

  /** Force applied sideways based on spin (px/s^2). */
  curveForce: 1200,

  /** Factor to scale drawing length to velocity for throw. */
  flickScalar: 3.5,

  /**
   * Wall bounce elasticity.
   * 1.0 = no energy loss (perfectly elastic).
   * 0.9 = slight damping (more natural feel).
   */
  wallBounceFactor: 1.0,

  /** Minimum pointer distance from launcher to register a shot (px). */
  minAimDistance: 30,
};

// ── Launcher Settings ───────────────────────────────────────────
export const LAUNCHER = {
  /** Max time in ms to keep pointer history for flick calculation */
  dragHistoryTime: 120,
};

// ── Trajectory Preview ──────────────────────────────────────────
export const TRAJECTORY = {
  /** Total number of preview dots along the path. */
  dotCount: 28,
  /** Distance between consecutive dots (px). */
  dotSpacing: 18,
  /** Visual radius of each dot (px). */
  dotRadius: 3,
  /** Maximum alpha of the leading dot (fades toward end). */
  dotAlpha: 0.35,
};

// ── Word Rules ──────────────────────────────────────────────────
export const WORD_RULES = {
  /** Minimum length of a valid word (also enforced in ItalianDictionary). */
  minLength: 3,
  /**
   * Maximum word length the DFS will explore.
   * Increase to allow longer words; decrease to improve performance.
   */
  maxLength: 15,
};

// ── Time Rules ──────────────────────────────────────────────────
export const GAME_DURATION_SECONDS = 120;

// ── Italian Letter Frequencies ──────────────────────────────────
/**
 * Approximate frequency weights for Italian text.
 * Higher number = more common in the bubble queue.
 * Edit weights to change the letter distribution.
 * Rare letters (Q, K, W, X, Y, J) intentionally omitted.
 */
export const LETTER_WEIGHTS: Record<string, number> = {
  A: 11.7,
  E: 11.8,
  I: 11.3,
  O: 9.8,
  U: 3.0,
  N: 6.9,
  L: 6.5,
  R: 6.4,
  T: 5.6,
  S: 5.0,
  C: 4.5,
  D: 3.7,
  P: 3.0,
  M: 2.5,
  V: 2.1,
  G: 1.6,
  H: 1.5,
  F: 1.1,
  B: 0.9,
  Z: 0.5,
};

// ── Italian Dictionary ──────────────────────────────────────────
// The full Italian dictionary is loaded at runtime from:
//   public/dictionaries/it.dawg
// That binary is generated by running:
//   node scripts/build-dawg.mjs
// See src/systems/ItalianDictionary.ts for the loader and format.

// ── Colours ─────────────────────────────────────────────────────
/** All colours as Phaser-compatible 0xRRGGBB hex integers or CSS strings. */
export const COLOURS = {
  // Surface
  background: 0xf9f9f7, // surface
  surfaceContainer: 0xeeeeec, // surface-container
  surfaceHighest: 0xe2e3e1, // surface-container-highest

  // Brand
  primary: 0x086c42, // Pastel Mint
  primaryContainer: 0x8ee4af,
  secondary: 0x9e3f49, // Soft Coral
  tertiary: 0x735c00, // Sunny Yellow
  tertiaryContainer: 0xf7ce48,

  // Bubbles
  bubbleVocal: 0x8ee4af, // primary-container
  bubbleConsonant: 0xe2e3e1, // surface-container-highest
  bubbleHighlight: 0x086c42, // primary
  bubbleGlow: 0x086c42,
  bubbleBorder: 0xbec9bf, // outline-variant
  bubbleLauncher: 0x086c42,

  // Text
  letterColour: '#1a1c1b', // on-surface
  hudText: '#1a1c1b',
  hudDim: '#3f4941', // on-surface-variant

  // UI
  trajectoryDot: 0xbec9bf, // outline-variant
  launcherRing: 0xbec9bf,
  wordFoundGreen: '#086c42',
  dangerLine: 0xba1a1a, // error
};
